resources:
# The repo with our Dockerfile
- name: concourse-poc
  type: git
  icon: github
  source:
    uri: https://github.com/Sparsh79/k6.git
    branch: master

- name: alias-cmd
  type: git
  icon: github
  source:
    uri: https://github.com/Sparsh79/KarateMaven.git
    branch: master

# Where we will push the image to
- name: con-example
  type: registry-image
  icon: docker
  source:
    repository: sparsh97/con-example
    username: sparsh97
    password: sparsh10!
    tag: latest


jobs:
- name: build-and-push
  plan:
  - aggregate:
     - get: concourse-poc 
     - get: alias-cmd
  - task: build-image
    file: concourse-poc/try.yml