on: [push]

jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run k6 load test
        uses: k6io/action@v0.1
        with:
          filename: post.js

      - uses: actions/upload-artifact@v2
        with:
          name: summary
          path: summary.html
      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: report
      #     path: summary.html
      #     retention-days: 2